version: '3.8'

services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9
    ports:
      - "535:53/udp"
      - "535:53/tcp"
    volumes:
      - ./config:/etc/bind
    restart: unless-stopped